name: Deploy to Render

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'SECURITY.md'
      - '.gitignore'

# Prevent multiple deploys from running simultaneously
concurrency:
  group: deploy-to-render
  cancel-in-progress: true

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest
    name: deploy-to-render
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Wait for potential auto-deploy
        run: |
          echo "Waiting 60 seconds to avoid conflicts with Render auto-deploy..."
          sleep 60

      - name: Trigger Render Deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "🚀 Triggering deployment for commit: ${{ github.sha }}"
          
          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/srv-d0971eeuk2gs73a2m2og/deploys)
          
          http_code="${response: -3}"
          body="${response%???}"
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" -eq 201 ] || [ "$http_code" -eq 200 ]; then
            echo "✅ Deployment triggered successfully!"
          else
            echo "❌ Deployment failed with status: $http_code"
            echo "Response: $body"
            exit 1
          fi
