name: Build and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "CODE_OF_CONDUCT.md"
      - "SECURITY.md"
      - ".gitignore"

# Prevent multiple builds from running simultaneously
concurrency:
  group: build-and-test
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level high

      - name: Build application
        run: |
          echo "🚀 Building WanderLust for commit: ${{ github.sha }}"
          echo "✅ Dependencies installed and security audit passed!"
          echo "📦 Application ready for deployment!"
          echo ""
          echo "🔗 Render will auto-deploy from this commit to:"
          echo "   https://wanderlust-c8cb.onrender.com"
